### ISSUE TITLE
口パク(簡易版）

### ISSUE THREAD

**Issue by yanoty3d** [smalab/CommuRobo#10]
まずは、音が流れている間に口がランダムに変化するようする（フォルマントはとらない）

**DOD**
- [x] 音の流れている間を検知する。
- [x] 音の流れている間に口が動く(動くパターンは任意）

**Comment by yanoty3d** [comment]
estimate = 8に設定

**Comment by yanoty3d** [comment]
完成しているので、コミットへのリンクを張ること。

**Comment by oitsmalab** [comment]
@459d9612e7f45b3803bd7a82b275fa5a54d3203f
