### ISSUE TITLE
認識した言葉に合わせて音声を流す

### ISSUE THREAD

**Issue by oitsmalab** [smalab/CommuRobo#13]
いくつかの単語（おはよう）などを認識させて、それに対する返答を音声ファイルで流す。

**DOD**
- [ ] 「音の流れている間に口を動かす」プロジェクトに音声認識エンジンが組み込まれている。 
- [ ] 認識した言葉に応じて反応する言葉とその音声ファイルを選び、それを流している間に口を動かす

**Comment by yanoty3d** [comment]
estimate = 8に設定
