### ISSUE TITLE
シナリオをアプリにする為のプロジェクトの準備

### ISSUE THREAD

**Issue by yanoty3d** [smalab/CommuRobo#16]
- [x] 各シーンにスプライト、ボタンを用意して、ボタンを押したらスコアを計算して別のシーンに遷移
- [x] スコアに対応したスプライトが表示されるようにする。

**Comment by oitsmalab** [comment]
@6431e4c

**Comment by oitsmalab** [comment]
シーン再生時、ボタンを押したときに音声が流れるようにした
ボタン押して、別のシーンへ遷移
顔の種類を増やしたい
