### ISSUE TITLE
スマホのジャイロセンサーを使って「座っている」「寝ている」などをとる。

### ISSUE THREAD

**Issue by yanoty3d** [smalab/CommuRobo#18]
ジャイロの加速度センサーなどで、体位を推測し、画面に表示。

**Comment by yanoty3d** [comment]
座る
寝る
激しく振る（加速度）
倒立
ゆっくり揺らす（ジャイロ）
持ちあげる
落とす
持ちあげる＋揺らす＝たかいたかい

public static class GetPostureState {

string posture; // standingUp, lyingDown, shaking, ...

public static string GetState(){
return posture;
}

---

GetPostureState.GetState()

**Comment by oitsmalab** [comment]
現在できているのは、座っている、寝ている、シェイクの3つ

**Comment by yanoty3d** [comment]
ゆっくり揺らす、はまだできていないが、大部分は実装できたといえる。
