### ISSUE TITLE
アバターの表情をつくる

### ISSUE THREAD

**Issue by oitsmalab** [smalab/CommuRobo#7]
瞬き、音に応じた口の開閉など、必要な顔の表情をPiskelのスプライトとして作る。

**DOD**
- [ ] 各母音に対応する口
- [ ] 目の瞬き
- [ ] 普通の顔と笑顔

**Comment by yanoty3d** [comment]
estimate = 2に設定

**Comment by yanoty3d** [comment]
コミット番号を書いておく
アセットへのリンクも書く

**Comment by oitsmalab** [comment]
https://drive.google.com/file/d/0B1IUVPG3GzFAaENZa1FFVE5rb3M/view?usp=sharing
